apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pihole

bases:
  - ../../base
commonLabels:
  context: prod

resources:
  - 03-pihole-pv-claims.yaml
patchesStrategicMerge:
  - 00-pihole-deploy-patch.yaml
  - 01-pihole-svc-patch.yaml
  - 02-ingress.yaml
