apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
`
resources:
  - 00-pihole-deployment.yaml
  - 01-pihole-svc.yaml 
  - 02-pihole-pv-claims.yaml
  - 03-ingress.yaml

secretGenerator:
- name: pihole-secret
  files:
  - webpasswd=./private/pihole-secret.yml
