apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pihole-ingress-testing
spec:
  ingressClassName: nginx
  rules:
  - host: dns.admin.theforlin.com 
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: pihole-svc
              port:
                number: 80 
        
